# values.yaml

app:
  name: crud-app
  labels:
    app: crud-app

image:
  repository: samuvel/crud-app
  tag: "v28"
  pullPolicy: IfNotPresent

deployment:
  replicas: 2
  podAnnotations: {}
  podLabels: {}
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 5000
  nodePort: 30001

volumes: []
volumeMounts: []
