version: '3.8'

services:
  crud-app:
    image: crud-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  
    depends_on:
      - mongodb
    networks:
      - crud-networks
      
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"  
    volumes:
      - mongodb_data:/data/db
    networks:
      - crud-networks  

networks:
  crud-networks:

volumes:
  mongodb_data:
