# values.yaml

# Application name and labels
app:
  name: crud-app
  labels:
    app: crud-app

# Image configuration
image:
  repository: samuvel/crud-app
  tag: latest
  pullPolicy: IfNotPresent

# Kubernetes deployment configuration
deployment:
  replicas: 2  # Number of replicas
  podAnnotations: {}
  podLabels: {}
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Service configuration
service:
  type: ClusterIP  # Can be ClusterIP, NodePort, or LoadBalancer
  port: 80
  targetPort: 5000
  nodePort: 30001  # Only used if service.type is NodePort

# Ingress configuration (optional)
ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - host: crud-app.local
      paths:
        - /
  tls: []

# Environment variables
env:
  MONGO_URI: "mongodb://mongodb:27017/Users"

# MongoDB configuration (optional if you manage MongoDB separately)
mongodb:
  enabled: true
  image:
    repository: samuvel/crud-db
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 27017
  persistence:
    enabled: false  # Set to true if you want to use persistent storage

# Volume mounts (if needed for persistence)
volumes: []
volumeMounts: []
